version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu

hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 120
      runas: ubuntu
    - location: delete.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
