version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "dilip/guvi"
    IMAGE_TAG: "${CODEBUILD_BUILD_NUMBER}"

phases:
  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR..."
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$(aws configure get region)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - echo "📦 Repository URI: ${REPOSITORY_URI}"

  build:
    commands:
      - echo "🏗️ Building the Docker image..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo "🚀 Pushing the Docker image to ECR..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo "✅ Image pushed successfully: ${REPOSITORY_URI}:${IMAGE_TAG}"
