version: 0.2

env:
  variables:
    IMAGE_NAME: dilip/guvi   # Replace with your ECR repo name
    AWS_DEFAULT_REGION: us-east-1    # Replace with your region
    ACCOUNT_ID: 380561001200         # Replace with your AWS account ID

phases:
  pre_build:
    commands:
      - echo "🔧 Installing dependencies..."
      - apt-get update && apt-get install -y curl wget unzip
      - echo " Downloading Dependency-Check..."
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
      - unzip dependency-check-12.1.0-release.zip -d /opt/
      - rm dependency-check-12.1.0-release.zip
      - export PATH=$PATH:/opt/dependency-check
      - echo " Dependency-Check installed."
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Setting image tag using build number...
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - mkdir -p dependency-check-reports
      - |
        /opt/dependency-check/bin/dependency-check.sh \
          --project "guvi-mini-project-1" \
          --scan dist \
          --out dependency-check-reports \
          --format "HTML"
      - echo "📄 Dependency-Check Reports Generated:"
      - ls -la dependency-check-reports
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - echo Image pushed successfully!
      - echo Sending email via SNS...
      - |
        aws sns publish \
          --topic-arn arn:aws:sns:us-east-1:380561001200:codebuild-notification \
          --subject "CodeBuild SUCCESS: $IMAGE_NAME:$IMAGE_TAG" \
          --message "CodeBuild job for project '$IMAGE_NAME' completed successfully.\n\nImage pushed to ECR: $IMAGE_TAG"

artifacts:
  files:
    - '**/*'