version: 0.2

env:
  variables:
    IMAGE_NAME: dilip/guvi   # Replace with your ECR repo name
    AWS_DEFAULT_REGION: us-east-1    # Replace with your region
    ACCOUNT_ID: 380561001200         # Replace with your AWS account ID

phases:
  pre_build:
    commands:
      - apt update && apt install -y gnupg curl
      - |
        OS_CODENAME=$(grep "VERSION_CODENAME" /etc/os-release | cut -d'=' -f2)
        curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor -o /usr/share/keyrings/trivy-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy-archive-keyring.gpg] https://aquasecurity.github.io/trivy-repo/deb $OS_CODENAME main" | tee /etc/apt/sources.list.d/trivy.list
        apt update && apt install -y trivy
        rm -rf /var/lib/apt/lists/*
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Setting image tag using build number...
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - trivy image --severity HIGH,CRITICAL --format table -o trivy-report.html $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - echo Pushing image to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - echo Image pushed successfully!

      - echo "🔧 Checking out main branch..."
      - git checkout main    

      - echo Updating deployment YAML with new image tag...
      - |
        sed -i "s|image: $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:.*|image: $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG|g" deployment.yml
        
      - echo "🔧 Configuring Git..."
      - git config --global user.email "codebuild@example.com"
      - git config --global user.name "AWS CodeBuild"

      - echo " Adding modified deployment.yml..."
      - git add deployment.yml

      - echo "Committing changes..."
      - git commit -m " Updated deployment tag to $IMAGE_TAG | CodeBuild"

      - echo " Updating remote URL with credentials (hidden)..."
      - git remote set-url origin https://$GIT_USERNAME:$GIT_TOKEN@github.com/Dilip-Devopos/guvi-mini-project-1.git

      - echo " Pushing to GitHub..."
      - git push origin main 

      - echo Sending email via SNS...
      - |
        aws sns publish \
          --topic-arn arn:aws:sns:us-east-1:380561001200:codebuild-notification \
          --subject "CodeBuild SUCCESS: $IMAGE_NAME:$IMAGE_TAG" \
          --message "CodeBuild job for project '$IMAGE_NAME' completed successfully.\n\nImage pushed to ECR: $IMAGE_TAG"

artifacts:
  files:
    - '**/*'