version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "🔧 Installing dependencies..."
      - apt-get update && apt-get install -y curl wget unzip
      - echo "⬇️ Downloading Dependency-Check..."
      - wget wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
      - unzip dependency-check-12.1.0-release.zip -d /opt/
      - rm dependency-check-12.1.0-release.zip
      - export PATH=$PATH:/opt/dependency-check
      - echo "✅ Dependency-Check installed."

  build:
    commands:
      - echo "🚀 Starting OWASP Dependency-Check..."
      - mkdir -p dependency-check-reports
      - |
        /opt/dependency-check/bin/dependency-check.sh \
          --project "guvi-mini-project-1" \
          --scan dist \
          --out dependency-check-reports \
          --format "ALL"
      - echo "📄 Dependency-Check Reports:"
      - ls -la dependency-check-reports

  post_build:
    commands:
      - echo "✅ Build completed"

artifacts:
  files:
    - dependency-check-reports/**