version: 0.2

phases:
  install:
    commands:
      - echo cloning repository........................................
      - apt-get update
  build:
    commands:
      - echo Build started on `date`
      - ls
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'

